version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Test123"
    ports:
      - "1433:1433"
  oracle:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle
    environment:
      ORACLE_PASSWORD: "Test123"
    ports:
      - "1521:1521"
  hazelcast:
    image: hazelcast/hazelcast:5.2
    container_name: hazelcast-node
    ports:
      - "5701:5701"
    depends_on:
      - sqlserver
      - oracle
  management-center:
    image: hazelcast/management-center:5.2
    container_name: hazelcast-mancenter
    ports:
      - "8080:8080"
    environment:
      HZ_MC_HAZELCAST_CLIENT_CLUSTER_NAME: "dev"
    depends_on:
      - hazelcast
networks:
  default:
    driver: bridge
